/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Article_DAO } from "./Article_DAO";
export * as factories from "./factories";
export { Article_DAO__factory } from "./factories/Article_DAO__factory";
